### ISSUE TITLE
The dataset does not match in ssr2.py

### ISSUE THREAD

**Issue by qqt-code** [yuelinan/codes-of-SSR#1]
in ssr2.py，the train dataset is 
![image](https://github.com/yuelinan/codes-of-SSR/assets/63205718/1105e3ec-c15c-487d-b2f3-e358ef310581)
but in dataset folder,,don't have the dataset.
![image](https://github.com/yuelinan/codes-of-SSR/assets/63205718/8d08faf1-3727-4314-a8cb-d43889569851)
Could you tell me how to solve this problem please?

**Comment by yuelinan** [comment]
Sorry, there should be an error in uploading, I'll upload a corrected dataset on a work day.

**Comment by qqt-code** [comment]
I apologize for bothering you again. In my understanding, the 'tag_ids' in the dataset indicate whether a word is rational, but I am not quite sure what 'shortcut_ids' represent. Could you please clarify this for me?

**Comment by yuelinan** [comment]
Hi, I've updated the dataset. Yes, the 'tag_ids' in the dataset indicate whether a word is rational. The 'shortcut_ids' indicate the potential shortcut tokens we inferred (Eq.5 in our paper).
By the way, may I ask if you and I are in the same lab? I noticed that the member of my lab 'qqt' has the same name as you.

**Comment by qqt-code** [comment]
Haha, yes, senior, I had the opportunity to read your paper and found it very interesting. Thank you for your explanation.

**Comment by yuelinan** [comment]
Wow! You can add me on WeChat!

**Comment by qqt-code** [comment]
Haha, really? Thank you, senior. My level might be a bit low, I hope I'm not bothering you too much, haha. My WeChat ID is 18674810708.

**Comment by yuelinan** [comment]
Hi, we can learn from each other and get better together!
